### ISSUE TITLE
sifdecode failed issue

### ISSUE THREAD

**Issue by Zheng321** [optimizers/homebrew-cutest#64]
Hi, I try to install CUTEst, including sifdecode. But it failed in testing sifdecode after I install/reinstall it. It also results in error when I use pycutest to read problems. I'm wondering if someone can help me! Thank you!

------------------------------ brew test sifdecode, error message -----------------------------
```
$ brew test sifdecode
==> Testing optimizers/cutest/sifdecode
==> /usr/local/Cellar/sifdecode/2.0.1_2/bin/sifdecoder /usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF
Last 15 lines from /Users/zhengy/Library/Logs/Homebrew/sifdecode/test.01.sifdecoder:
2022-09-26 16:39:56 +0800

/usr/local/Cellar/sifdecode/2.0.1_2/bin/sifdecoder
/usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF

dyld[60987]: Library not loaded: '/usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib'
  Referenced from: '/usr/local/Cellar/sifdecode/2.0.1_2/libexec/objects/mac64.osx.gfo/double/run_sifdecode'
  Reason: tried: '/usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file)
/usr/local/Cellar/sifdecode/2.0.1_2/bin/sifdecoder: line 451: 60987 Abort trap: 6           $DECODER

 ERROR: Error exit from decoding stage. terminating execution.

Error: optimizers/cutest/sifdecode: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/sifdecode/2.0.1_2/bin/sifdecoder /usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF
/usr/local/Homebrew/Library/Homebrew/formula.rb:2493:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2429:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2429:in `system'
/usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:85:in `block (2 levels) in <class:Sifdecode>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
/usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:84:in `block in <class:Sifdecode>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2269:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2268:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2267:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2544:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2261:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
```
------------------------------ pycutest, error message -----------------------------
```
$ python pdProj.py TAME 
/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/__init__.py:28: RuntimeWarning: the PYCUTEST_CACHE environment variable is not set; current folder will be used for caching.
  warnings.warn("the PYCUTEST_CACHE environment variable is not set; current folder will be used for caching.", RuntimeWarning)
dyld[61578]: Library not loaded: '/usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib'
  Referenced from: '/usr/local/Cellar/sifdecode/2.0.1_2/libexec/objects/mac64.osx.gfo/double/run_sifdecode'
  Reason: tried: '/usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file)
/usr/local/opt/sifdecode/libexec/bin/sifdecoder: line 451: 61578 Abort trap: 6           $DECODER

 ERROR: Error exit from decoding stage. terminating execution.


Traceback (most recent call last):
  File "/Users/zhengy/Documents/MdoPSIPM/MdoPSIPM-code/src/pdProj.py", line 1707, in <module>
    main()
  File "/Users/zhengy/Documents/MdoPSIPM/MdoPSIPM-code/src/pdProj.py", line 1684, in main
    prob = pycutest.import_problem(prob)
  File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/build_interface.py", line 339, in import_problem
    objList = decode_and_compile_problem(problemName, destination, sifParams, sifOptions, quiet)
  File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/build_interface.py", line 214, in decode_and_compile_problem
    raise RuntimeError('SIFDECODE failed, check output printed above')
RuntimeError: SIFDECODE failed, check output printed above
```
Thank you for the help!

**Comment by Zheng321** [comment]
Just to update: I note the error message for failing testing sifdecode tries to find libgfortran.5.dylib at a wrong place.

Reason: tried: '/usr/local/opt/gcc/lib/gcc/11/libgfortran.5.dylib' (no such file)
But I am able to locate it in /usr/local/opt/gcc/lib/gcc/**12**/libgfortran.5.dylib

Is this the possible reason? How can I fix this elegantly? Thank you!

**Comment by dpo** [comment]
@Zheng321 For future reference, you can enclose code and output between triple backticks. It makes them much easier to read.

What may have happened is that you updated gcc/gfortran after you installed SIFDecode?!

Could you simply try `brew reinstall sifdecode`?

**Comment by Zheng321** [comment]
Thank you for replying! I will use triple backticks in the future!

I tried several times, including reinstalling everything including cutest, sifdecode, gcc using brew. But it always tries to find sifdecode in folder 11 while my installation is in folder 12.

One way to deal with it, is simply rename the folder 12 to 11. It works in some sense, as the ```brew test sifdecode``` will pass with no error. However, when I continue to install pycutest and import this package, another error jumps out:

```
Traceback (most recent call last):
File "/Users/zhengy/Documents/src/pdProj.py", line 1707, in
main()
File "/Users/zhengy/Documents/src/pdProj.py", line 1682, in main
import pycutest
File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/init.py", line 9, in
from .build_interface import import_problem, clear_cache, all_cached_problems
File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/build_interface.py", line 16, in
from .install_scripts import get_setup_script
File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/install_scripts.py", line 97, in
""" % get_cutest_path() # will probably get the homebrew location, but may revert to environment variables
File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/system_paths.py", line 40, in get_cutest_path
raise RuntimeError('Could not find CUTEST installation - have CUTEST and MYARCH environment variables been set correctly?')
RuntimeError: Could not find CUTEST installation - have CUTEST and MYARCH environment variables been set correctly?
```

I note that in the error message, the get_cutest_path() function in File "/Users/zhengy/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/system_paths.py" raise this error, so I went into it. Here is the relavent codes: (I'm using Mac)

```
def get_cutest_path():
    if sys.platform == 'darwin':  # Mac
        # First try environment variables, otherwise use default homebrew location
        if 'CUTEST' in os.environ and 'MYARCH' in os.environ:
            cutest_path = os.path.join(os.environ['CUTEST'], 'objects', os.environ['MYARCH'], 'double', 'libcutest.a')
            if os.path.isfile(cutest_path):
                return cutest_path
        homebrew_path = os.path.join('usr', 'local', 'opt', 'cutest', 'lib', 'libcutest.a')  # /usr/local/opt/cutest/lib/libcutest.a
        if os.path.isfile(homebrew_path):
            return homebrew_path
        else:
            raise RuntimeError('Could not find CUTEST installation - have CUTEST and MYARCH environment variables been set correctly?')
```

I'm confused bc I notices that "/usr/local/opt/cutest/lib/libcutest.a" is a valid file on my end.

```
$ pwd
/usr/local/opt/cutest/lib
$ ls
libcutest.a		libcutest_double.a	libcutest_single.a
libcutest.dylib		libcutest_double.dylib	libcutest_single.dylib
```

Thus, from my understanding (I'm a newbie in coding),  ```homebrew_path = os.path.join('usr', 'local', 'opt', 'cutest', 'lib', 'libcutest.a')``` is a valid file and should be returned, instead of raising an Runtime error. I'm not sure what should I approach at this point. Thank you for the help if you have any idea!

**Comment by Zheng321** [comment]
Update:

I note ```homebrew_path = os.path.join('usr', 'local', 'opt', 'cutest', 'lib', 'libcutest.a')``` gives ```usr/local/opt/cutest/lib/libcutest.a```, which is not a file. It miss a ```\``` at the beginning. I try to fix this by updating the codes to ```homebrew_path = os.path.join('\usr', 'local', 'opt', 'cutest', 'lib', 'libcutest.a')``` in ```system_paths.py```. I did this to all get_path functions for cutest, sifdecode, etc.. and is able to import pycutest.

When I try to read problem by ```pycutest.import_problem('TAME')```, sifdecode errors indicating environment variables not set jump out. Thus, I try to include the following codes to add environment variables.
```
os.environ['ARCHDEFS'] = '/usr/local/opt/archdefs/libexec'
os.environ['SIFDECODE'] = '/usr/local/opt/sifdecode/libexec'
os.environ['MYARCH'] = 'mac64.osx.gfo'
os.environ['MASTSIF'] = '/usr/local/opt/mastsif/share/mastsif'
os.environ['CUTEST'] = '/usr/local/opt/cutest/libexec'
```

The environment variable error is gone, but the newest issue is the following:
```
AttributeError                            Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 pycutest.import_problem('TAME')

File ~/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/build_interface.py:348, in import_problem(problemName, destination, sifParams, sifOptions, efirst, lfirst, nvfirst, quiet, drop_fixed_variables)
    346 # Import the module CACHE_SUBFOLDER.problemDir, and return a wrapper
    347 try:
--> 348     return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
    349                          drop_fixed_variables=drop_fixed_variables)
    350 except ImportError as error:
    351     try: # check if cache folder is on python path

File ~/opt/miniconda3/envs/env3.10/lib/python3.10/site-packages/pycutest/problem_class.py:82, in CUTEstProblem.__init__(self, module, drop_fixed_variables)
     78 self.drop_fixed_vars = drop_fixed_variables
     80 # Extract useful problem info
---> 82 self.name = self._module.info['name']
     83 """ CUTEst problem name (string) """
     85 self.n = self._module.info['n']

AttributeError: module 'pycutest_cache_holder.TAME' has no attribute 'info'
```

I don't feel I'm on the right way to go, any suggestions please? I think I followed the installation for mac exactly, and redo it several times. I really don't know where I did wrong. Thank you so much for the help!

**Comment by dpo** [comment]
This is not the repository for PyCUTEST and I have nothing to do with that package. You would have better luck asking the authors directly.

**Comment by Zheng321** [comment]
Thank you! I will ask in that repo!
